id: IC8A15B83
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T07:56:55+00:00'
last_modified: '2022-06-08T05:05:20.344912+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1PD159389
  title: ཉག་བྲོ་ཐང་དཀར་རྒོད་པོའི་གཤོག་འགྱུར།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    813C:
      image_group_id: I2PD19652
      title: ''
      total_pages: 354
      order: 1
      base_file: 813C.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
